version: '3.3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - myvolume:/var/lib/mysql
      - ./sql:/sql
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 9000:80
    depends_on:
      - db
  react:
    build: ./react/
    command: npm start
    volumes:
      - ./react/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
volumes:
  myvolume:
