# Generated by Django 2.0.13 on 2019-08-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190815_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pedido',
            field=models.IntegerField(default=0),
        ),
    ]
